// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-0UgZ22HYVsQ1r7HDq0o_udLmdDOvbk',
    appId: '1:933603292292:web:5739abd8cbda1593557ed1',
    messagingSenderId: '933603292292',
    projectId: 'noteapp-11cab',
    authDomain: 'noteapp-11cab.firebaseapp.com',
    storageBucket: 'noteapp-11cab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxB_fuZGc9ENkI2RZ0dMOpiZfNfSpgrqQ',
    appId: '1:933603292292:android:1fbd9fda9de52897557ed1',
    messagingSenderId: '933603292292',
    projectId: 'noteapp-11cab',
    storageBucket: 'noteapp-11cab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSoJmQ-_wQXZBW9bkt-ZfvxO8ungb23IM',
    appId: '1:933603292292:ios:ca71e8b1d28d39e5557ed1',
    messagingSenderId: '933603292292',
    projectId: 'noteapp-11cab',
    storageBucket: 'noteapp-11cab.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSoJmQ-_wQXZBW9bkt-ZfvxO8ungb23IM',
    appId: '1:933603292292:ios:ca71e8b1d28d39e5557ed1',
    messagingSenderId: '933603292292',
    projectId: 'noteapp-11cab',
    storageBucket: 'noteapp-11cab.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0-0UgZ22HYVsQ1r7HDq0o_udLmdDOvbk',
    appId: '1:933603292292:web:25a78dca2e26085e557ed1',
    messagingSenderId: '933603292292',
    projectId: 'noteapp-11cab',
    authDomain: 'noteapp-11cab.firebaseapp.com',
    storageBucket: 'noteapp-11cab.firebasestorage.app',
  );
}
